pipeline {
    agent any

    stages {
        stage('init') {
            steps {
                git url: 'https://github.com/Passive1412/jgsu-spring-petclinic.git',
                branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean package'
            }

            post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
